// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type UserDetailRequest struct {
	Id     int    `json:"id"`
	Tall   int32  `json:"tall"`
	Email  string `json:"email"`
	Sex    string `json:"sex"`
	Hobbit string `json:"hobbit"`
}

type UserDetailResponse struct {
	Message string `json:"message"`
}

type UserInfoRequest struct {
	Id int `json:"id"`
}

type UserInfoResponse struct {
	Tall   int32  `json:"tall"`
	Eamil  string `json:"eamil"`
	Sex    string `json:"sex"`
	Hobbit string `json:"hobbit"`
}

type UserDeleteRequest struct {
	Id int `json:"id"`
}

type UserDeleteResponse struct {
	Message string `json:"message"`
}

type UserUpdateRequest struct {
	Id     int    `json:"id"`
	Sex    string `json:"sex"`
	Email  string `json:"email"`
	Hobbit string `json:"hobbit"`
	Tall   int32  `json:"tall"`
}

type UserUpdateResponse struct {
	Message string `json:"message"`
}
